### ISSUE TITLE
Installation instructions wrong

### ISSUE THREAD

**Issue by petef4** [druths/arghandler#1]
https://github.com/druths/arghandler#installation

In many instances such as pip install you say argparse where you mean arghandler.

**Comment by druths** [comment]
Shoot – thanks for pointing it out.  I’ve fixed it and released a patch … that was a bad enough documentation error that it needed to be pushed out.

**Comment by petef4** [comment]
You missed one "You can find argparse on pypi ..."

**Comment by druths** [comment]
Arg.  Fixed.
