### ISSUE TITLE
help unexpected

### ISSUE THREAD

**Issue by dpwrussell** [druths/arghandler#13]
From one of the examples in the README.

``` python
#!/usr/bin/env python

from arghandler import ArgumentHandler, subcmd

@subcmd('foobar', help='Does foobar')
def cmd_foobar(parser, context, args):
    print 'foobar'

handler = ArgumentHandler()
handler.run(['echo','hello','world'])
```

```
Traceback (most recent call last):
  File "./manager.py", line 5, in <module>
    @subcmd('foobar', help='Does foobar')
TypeError: subcmd() got an unexpected keyword argument 'help'
```

``` sh
$ pip list | grep arghandler
arghandler (1.1.0)
```

**Comment by druths** [comment]
Shoot - fixing this now.

**Comment by druths** [comment]
Oh - this isn't a 1.1.0 version feature.  It's currently in the trunk.  I'll release a new version so it's in sync - but you'll have to install the latest version from pypi once it's there.

**Comment by dpwrussell** [comment]
Yeah, I thought it might be that, but as there was no GitHub release/tag for 1.1.0 I wasn't sure if it was supposed to be there or not.

Cheers

**Comment by druths** [comment]
Totally my mistake.  Still learning the ins and outs of versioning code :)  It's all set to go now on pypi.  There's a 1.2.0 version there now with this feature.

**Comment by dpwrussell** [comment]
No probs. I think the best thing to do is create the release on GitHub as well, that way there is a record of exactly which commit the release _is_.

**Comment by druths** [comment]
Thanks for the tip – I just created the v1.2.0 release on github as well.  Will do that from here on out.
