### ISSUE TITLE
Recursive subcommands?

### ISSUE THREAD

**Issue by AndreaCrotti** [druths/arghandler#14]
Would it be possible do have something like

```
    ./script.py <command> <sub-command>
```

I tried somethinig like

```
@subcmd('cmd')
def cmd(...):
     @subcmd('other')
     def other(...)
```

but I guess it's not supported..

**Comment by druths** [comment]
You could do this with multiple ArgumentHandlers... But you couldn't use the @subcmd helper functions.

Derek Ruths
Associate Professor
School of Computer Science
McGill University

www.derekruths.com
@derekruths

**Comment by AndreaCrotti** [comment]
Ah I see, well as long as we can achieve the same result it's fine it doesn't have to be with subcmd necessarily..
