### ISSUE TITLE
How to set the help description of a subcommand?

### ISSUE THREAD

**Issue by Helveg** [druths/arghandler#20]
So, I'm a bit confused on how to generate help for a subcommand, could you create an example like the echo example in the README but where the help lists the subcommands with a help message for the 'echo' and 'foo' subcommands and their arguments? In the subcommand I use `parser.add_argument("something",help="Help text")` but how do I set a help text for a subcommand?

**Comment by barny** [comment]
Using the decorators is so neat - instead of

`@subcmd('echo')
`

use e.g.:

`@subcmd('echo',help='This subcommand echoes what you input')
`

Or what I do is give the function the name of the command so it doesn't need to be in the decorator, and then the decorator becomes:

```
@subcmd(help='This subcommand echoes what you input')
def echo(parser,context,topargs):
    parser.add_argument('var',help='The variable')
    parser.add_argument('value',help='Value')
    args = parser.parse_args(topargs)
    ...
```

**Comment by Helveg** [comment]
Oh nice!
