### ISSUE TITLE
Using positional arguments in a sub-command shows warning

### ISSUE THREAD

**Issue by kewisch** [druths/arghandler#3]
Going by the readme docs, I've added this kind of code:

``` python
@subcmd('get')
def cmd_get(ctxt, args):
    handler = ArgumentHandler()
    handler.ignore_subcommands()
    handler.add_argument('-o', '--outdir', default=os.getcwd(), help='output directory')
    handler.add_argument('-l', '--limit', type=int, default=1, help='number of versions to download')
    handler.add_argument('thingy', help='the thingy get')
    args = handler.parse_args(args)
```

When executing I get this warning: `warning: subcommands are not going to be used`. Am I doing it wrong or is this a bug?

**Comment by druths** [comment]
To get the subcommand functionality, you need to call handler.run, not parse_args.

**Comment by kewisch** [comment]
I am calling `handler.run` in the main loop, but the above sample is from the subcommand and matches what is in the documentation. Here is a more complete snippet:

``` python
@subcmd('get')
def cmd_get(ctxt, args):
    sub_handler = ArgumentHandler()
    sub_handler.ignore_subcommands()
    sub_handler.add_argument('-o', '--outdir', default=os.getcwd(), help='output directory')
    sub_handler.add_argument('-l', '--limit', type=int, default=1, help='number of versions to download')
    sub_handler.add_argument('thingy', help='the thingy get')
    args = sub_handler.parse_args(args)

    do_things_with(args)

def main():
    thing = ThingService()

    handler = ArgumentHandler()
    handler.add_argument('-g', '--global', help='Some global argument')
    handler.run(sys.argv[1:], context_fxn=lambda _: thing)

if __name__ == '__main__':
    main()
```

Maybe you can clarify what I would need to do to:
- Support global arguments, as opposed to per-subcommand arguments
- Make use of subcommands
- Let subcommands have both positional and named arguments

**Comment by druths** [comment]
Oh - I see what you're trying to do.  Yeah, a warning shouldn't be generated there.  I've just pushed a fix to this to the trunk.
