### ISSUE TITLE
Make compatible with argcomplete

### ISSUE THREAD

**Issue by chris-codaio** [druths/arghandler#8]
Enabling bash autocompletion with arghandler would be very powerful.

**Comment by druths** [comment]
That would be cool! Can you point me to any Python libraries that support that (to get an idea of how best to do this).

**Comment by chris-codaio** [comment]
https://github.com/kislyuk/argcomplete works out-of-the-box with argparse today.  I suspect integration would be pretty trivial with some tweaks.

**Comment by druths** [comment]
Thanks for the recommendation here.  I've incorporated argcomplete.  It works great!

**Comment by chris-codaio** [comment]
Excellent - thanks!  I'll try it out soon.
